language: erlang
before_install:
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout z3-4.4.1
  - python scripts/mk_make.py
  - cd build
  - make -j 4
  - sudo make install
  - cd ../..
script:
  - git submodule update
  - git submodule foreach make
  - export ERL_LIBS=$PWD/lib/proper:$ERL_LIBS
  - autoconf
  - ./configure
  - make depend
  - make all
  - cd doc/smt2/; python3 -m unittest discover test
otp_release:
  - 19.0
  - 18.3
  - 18.1	# 18.0 has a problem in dialyzer
